// editors/blocknote-headless/src/vue/blocks/LinkEditor.vue
<!--
See the LICENSE file distributed with this work for additional
information regarding copyright ownership.

This is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License as
published by the Free Software Foundation; either version 2.1 of
the License, or (at your option) any later version.

This software is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this software; if not, write to the Free
Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
02110-1301 USA, or see the FSF site: http://www.fsf.org.
-->
<script setup lang="ts">
import { LinkEditionContext } from "../../components/linkEditionContext";
import { LinkSuggestion } from "../../components/linkSuggest";
import { CIcon } from "@xwiki/cristal-icons";
import { LinkType } from "@xwiki/cristal-link-suggest-api";
import { EntityReference } from "@xwiki/cristal-model-api";
import { debounce } from "lodash-es";
import { ref } from "vue";

const { linkEditionCtx, current, hideTitle } = defineProps<{
  linkEditionCtx: LinkEditionContext;
  current: {
    title: string;
    reference: EntityReference | null;
    url: string;
  } | null;
  hideTitle?: boolean;
}>();

const emit = defineEmits<{
  update: [{ title: string; reference: EntityReference | null; url: string }];
}>();

const target = ref({
  url: current?.url ?? "",
  reference: current?.reference ?? null,
});

const title = ref(current?.title ?? "");

const results = ref<LinkSuggestion[]>([]);

const query = ref(
  (current?.reference
    ? linkEditionCtx.modelReferenceSerializer.serialize(current.reference)
    : current?.url) ?? "",
);

const search = debounce(async (query: string) => {
  target.value = { url: query, reference: null };

  if (query.startsWith("http://") || query.startsWith("https://")) {
    results.value = [];
    return;
  }

  const suggestions = await linkEditionCtx.suggestLink({ query });

  results.value = suggestions.filter(
    (suggestion) => suggestion.type === LinkType.PAGE,
  );
});

function select(result: LinkSuggestion) {
  title.value ||= result.title;
  query.value = result.title;
  target.value = {
    url: result.url,
    reference: linkEditionCtx.modelReferenceParser.parse(result.reference),
  };
  results.value = [];
}

function submit() {
  emit("update", {
    title: title.value,
    url: target.value.url,
    reference: target.value.reference,
  });
}
</script>

<template>
  <div class="fields">
    <template v-if="!hideTitle">
      <label>
        <c-icon name="tag" />
      </label>

      <input v-model="title" type="text" placeholder="Title" />
    </template>

    <label>
      <c-icon name="link" />
    </label>

    <input
      v-model="query"
      type="text"
      placeholder="URL or page reference"
      @input="search(query)"
    />

    <x-btn @click="submit">Save</x-btn>
  </div>

  <div v-if="results.length > 0">
    <hr />

    <ul>
      <li
        v-for="result in results"
        :key="result.url"
        class="search-result"
        @click="select(result)"
      >
        {{ result.title }}
      </li>
    </ul>
  </div>
</template>

<style scoped>
.fields {
  margin: 10px;
  display: grid;
  grid-template-columns: [labels] auto [controls] 1fr;
  grid-auto-flow: row;
  gap: 5px;
}

.fields > label {
  grid-column: labels;
  grid-row: auto;
}

.fields > input,
.fields > button {
  grid-column: controls;
  grid-row: auto;
  outline: none;
}

input {
  border: 1px solid lightgray;
  padding: 5px;
}

.search-result {
  cursor: pointer;
}

.search-result:hover {
  text-decoration: underline;
}
</style>

// editors/blocknote-react/src/components/links/LinkEditor.tsx
/*
 * See the LICENSE file distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */
import {
  LinkEditionContext,
  LinkSuggestion,
  createLinkSuggestor,
} from "../../misc/linkSuggest";
import { Autocomplete, Input, Stack } from "@mantine/core";
import { debounce } from "@xwiki/cristal-fn-utils";
import { LinkType } from "@xwiki/cristal-link-suggest-api";
import { EntityReference } from "@xwiki/cristal-model-api";
import { useCallback, useState } from "react";
import { RiLink, RiText } from "react-icons/ri";

type LinkData = {
  title: string;
  reference: EntityReference | null;
  url: string;
};

type LinkEditorProps = {
  linkEditionCtx: LinkEditionContext;
  current: LinkData | null;
  updateLink: (linkData: LinkData) => void;
  hideTitle?: boolean;
};

export const LinkEditor: React.FC<LinkEditorProps> = ({
  linkEditionCtx,
  current,
  updateLink,
  hideTitle,
}) => {
  const suggestLink = createLinkSuggestor(linkEditionCtx);

  const [customTitle, setCustomTitle] = useState(current?.title ?? "");
  const [results, setResults] = useState<
    (LinkSuggestion | { type: "url"; title: string; url: string })[]
  >([]);

  const search = useCallback(
    debounce(async (query: string) => {
      if (query.startsWith("http://") || query.startsWith("https://")) {
        setResults([{ type: "url", title: query, url: query }]);
        return;
      }

      const suggestions = await suggestLink({ query });

      setResults(
        suggestions.filter((suggestion) => suggestion.type === LinkType.PAGE),
      );
    }),
    [setResults],
  );

  const submit = useCallback(
    ({
      title,
      url,
      reference,
    }: {
      title: string;
      url: string;
      reference: EntityReference | null;
    }) => {
      const result = results.find((result) => result.title === title);

      if (!result) {
        return;
      }

      updateLink({
        title,
        url,
        reference,
      });
    },
    [results, setResults],
  );

  const selectFromTitle = useCallback(
    (title: string) => {
      const result = results.find((result) => result.title === title)!;

      submit({
        title: customTitle || title,
        url: result.url,
        reference:
          result.type === "url"
            ? null
            : linkEditionCtx.remoteURLParser.parse(result.reference)!,
      });
    },
    [results, customTitle, submit],
  );

  return (
    <Stack>
      {!hideTitle && (
        <Input
          leftSection={<RiText />}
          value={customTitle}
          onChange={(e) => setCustomTitle(e.target.value)}
          onKeyDown={(e) =>
            current &&
            e.key === "Enter" &&
            submit({
              title: customTitle,
              url: current.url,
              reference: current.reference,
            })
          }
        />
      )}

      <Autocomplete
        leftSection={<RiLink />}
        data={results.map((result) => ({
          value: result.title,
        }))}
        defaultValue={
          current?.reference
            ? (linkEditionCtx.modelReferenceSerializer.serialize(
                current.reference,
              ) ?? current.url)
            : ""
        }
        onInput={(e) => {
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          search((e.target as any).value);
        }}
        onChange={(e) => {
          selectFromTitle(e);
        }}
        comboboxProps={{ zIndex: 10000 }}
      />
    </Stack>
  );
};

export type { LinkData, LinkEditorProps };
